on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Setup target Node.js to enable Corepack
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Enable Corepack
        run: corepack enable
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn build-all
      - name: deploy page
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}